//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIENMAYQUYETTIEN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public Product()
        {
            this.CashBillDetails = new HashSet<CashBillDetail>();
            this.InstallmentBillDetails = new HashSet<InstallmentBillDetail>();
        }
    
        public int ID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        [Required (ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        public int ProductTypeID { get; set; }
        public int SalePrice { get; set; }
        [Required (ErrorMessage = "Vui lòng nhập giá bán sản phẩm")]
        [Range (50, 100000000, ErrorMessage = "Giá sản phẩm không được nhỏ hơn 50 và lớn hơn 100 000 000")]
        public int OriginPrice { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá gốc sản phẩm")]
        [Range(50, 100000000, ErrorMessage = "Giá sản phẩm không được nhỏ hơn 50 và lớn hơn 100 000 000")]
        public int InstallmentPrice { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá trả góp sản phẩm")]
        [Range(50, 100000000, ErrorMessage = "Giá sản phẩm không được nhỏ hơn 50 và lớn hơn 100 000 000")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá sản phẩm")]
        [Range(50, 100000000, ErrorMessage = "Giá sản phẩm không được nhỏ hơn 50 và lớn hơn 100 000 000")]
        public string Avatar { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<CashBillDetail> CashBillDetails { get; set; }
        public virtual ICollection<InstallmentBillDetail> InstallmentBillDetails { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
